- name: Initial server setup 
  hosts: localhost
  connection: local
  become: true
  tasks: 
    - name: Perform a dist-upgrade
      apt:
        upgrade: dist
        update_cache: yes
    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file
    - name: Reboot the server (if required)
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Install basic tools
      apt:
        name: "{{item}}"
        state: latest
      loop:
        - build-essential
        - curl
        - wget
        - git
        - file
        - procps
        - screen
        - vim

    - name: Copy config for screen
      become: false
      get_url:
        url: https://raw.githubusercontent.com/designtypist/configs/master/.screenrc
        dest: ~/.screenrc
        mode: '0664'
    - name: Copy config for vim
      become: false
      get_url:
        url: https://raw.githubusercontent.com/designtypist/configs/master/.vimrc
        dest: ~/.vimrc
        mode: '0664'

#    - name: Install bash-it  
      # git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
      # ~/.bash_it/install.sh
    
    - name: Remove dependencies that are no longer required.
      apt:
        autoremove: yes
